export type MemoryType = 'url' | 'text' | 'image' | 'audio' | 'file';
export type Sentiment = 'positive' | 'neutral' | 'negative';

export interface Entity {
  type: 'person' | 'place' | 'organization' | 'date' | 'other';
  value: string;
  confidence: number;
}

export interface Memory {
  id: string;
  userId?: string;
  type: MemoryType;

  // Original content
  content: string;
  originalUrl?: string;
  fileUrl?: string;
  fileName?: string;
  fileSize?: number;
  mimeType?: string;

  // AI-generated metadata
  title: string;
  summary?: string;

  // Classification
  categories: string[];
  tags: string[];
  topics: string[];
  entities: Entity[];
  sentiment?: Sentiment;
  language?: string;

  // Organization
  collectionIds: string[];
  isFavorite: boolean;
  isArchived: boolean;
  importance: number;

  // Metadata
  source?: string;
  createdAt: Date;
  updatedAt: Date;
  accessedAt: Date;
  accessCount: number;
}

export interface Collection {
  id: string;
  userId?: string;
  name: string;
  description?: string;
  isAutoGenerated: boolean;
  memoryIds: string[];
  color?: string;
  icon?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateMemoryInput {
  type: MemoryType;
  content: string;
  originalUrl?: string;
  fileUrl?: string;
  fileName?: string;
  source?: string;
}
